FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install --legacy-peer-deps --save-dev @vitejs/plugin-react


COPY . .

RUN npm run build 

FROM alpine
WORKDIR /dist
COPY --from=build /app/dist .
CMD ["sleep", "infinity"]
