provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false

userconfig:
  service:
    extensions: [jaeger_storage, jaeger_query, healthcheckv2, remote_sampling, zpages, expvar, jaeger_mcp]
    pipelines:
      traces:
        receivers: [otlp, jaeger]
        exporters: [jaeger_storage_exporter]

  extensions:
    healthcheckv2:
      use_v2: true
      http:
        endpoint: 0.0.0.0:13133

    jaeger_storage:
      backends:
        some_storage:
          memory:
            max_traces: 50000

    jaeger_query:
      storage:
        traces: some_storage
      base_path: /jaeger

    remote_sampling:
      file:
        path: ""

    zpages:
      endpoint: 0.0.0.0:27778

    expvar:
      endpoint: "[::]:27777"

    jaeger_mcp:
      http:
        endpoint: 0.0.0.0:16687

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_http:
          endpoint: 0.0.0.0:14268
        thrift_binary:
          endpoint: 0.0.0.0:6832
        thrift_compact:
          endpoint: 0.0.0.0:6831

  exporters:
    jaeger_storage_exporter:
      trace_storage: some_storage

jaeger:
  enabled: true

storage:
  type: memory

serviceMonitor:
  enabled: true
  additionalLabels:
    release: kube-prometheus-stack