FROM node:24-bookworm-slim AS builder
WORKDIR /app
COPY *.json .
RUN npm install
COPY . .
RUN npm run build

FROM alpine:latest
COPY --from=builder /app/dist /dist
RUN chmod -R 755 /dist
CMD ["sh", "-c", "cp -r /dist/. /output/ && echo 'Done'"]
