server {
    listen 80;
    server_name localhost;

    location /notes/api/ {
        proxy_pass http://notes-backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /notes/ {
        root /apps;
        try_files $uri $uri/ /notes/index.html;
    }

    location /bank/api/ {
        proxy_pass http://bank-backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /bank/ {
        root /apps;
        try_files $uri $uri/ /bank/index.html;
    }

    location /quiz/ {
        root /apps;
        try_files $uri $uri/ /quiz/index.html;
    }

    location /video/api/ {
        proxy_pass http://video-uploader-backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /video/ {
        root /apps;
        try_files $uri $uri/ /video/index.html;
    }

    location /hospital/ {
        proxy_pass http://hospital-management:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /blog/ {
        proxy_pass http://blog-website:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /social/ {
        proxy_pass http://172.18.0.2:30080/social/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        return 200 '{"status":"gateway running","apps":["/notes/","/bank/","/quiz/","/video/","/hospital/","/blog/","/social/"]}';
        add_header Content-Type application/json;
    }
}