apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: socialmediaapp-django:latest
          imagePullPolicy: Never
      startupProbe:
          exec:
            command:
            - python
            - -c
            - "import socket; socket.create_connection(('postgres', 5432), timeout=1)"
          failureThreshold: 30
          periodSeconds: 5
          ports:
            - containerPort: 8000

          env:
            - name: DB_NAME
              value: socialdb
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: password
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"

            - name: DEBUG
              value: "True"

            - name: RUNNING_IN_DOCKER
              value: "True"
